
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: care-production-celery-worker
spec:
  template:
    metadata:
      labels:
        name: care-production-celery-worker
        app: care-production-celery-worker
        env: production
        namespace: default
    spec:
      containers:
        - name: care
          image: accountid.dkr.ecr.ap-south-1.amazonaws.com/care:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: newrelic-ini
              mountPath: /etc/newrelic.ini
              subPath: newrelic.ini
          resources:
              requests:
                  memory: "4000Mi"
                  cpu: "1"
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "newrelic-admin run-program celery --app=config.celery_app --loglevel=info worker" ]
          ports:
            - containerPort: 9000
              name: django
              protocol: TCP
          envFrom:
          - configMapRef:
              name: care-production
          - secretRef:
              name: care-production
          env:
            - name: RESTART_
              value: "20200331015742"
      volumes:
        - name: newrelic-ini
          secret:
            secretName: care-production
            items:
              - key: NEWRELIC_INI
                path: newrelic.ini