apiVersion: v1
kind: Secret
metadata:
  name: care-production
  labels:
    app: care
    env: production
    namespace: default
type: Opaque
data: // all entries must be in base64 encoded format for data
  POSTGRES_PASSWORD: ''
  POSTGIS_URL: ''
  REDIS_URL: ''
  SENTRY_DSN: ''
  DJANGO_ADMIN_URL: ''
  DJANGO_SECRET_KEY: ''
  GOOGLE_RECAPTCHA_SITE_KEY: ''
  GOOGLE_RECAPTCHA_SECRET_KEY: ''
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  NEWRELIC_INI: ''
  VAPID_PUBLIC_KEY: ''
  VAPID_PRIVATE_KEY: ''
stringData: // normal string entries
  CELERY_BROKER_URL: 'redis://:@redis-cache-production:6379/0'
  FERNET_SECRET_KEY: ''
  CURRENT_DOMAIN: ''
  EMAIL_HOST: 'email-smtp.ap-south-1.amazonaws.com'
  EMAIL_USER: ''
  EMAIL_PASSWORD: ''
  SNS_ACCESS_KEY: ''
  SNS_SECRET_KEY: ''
  FILE_UPLOAD_BUCKET: ""
  FILE_UPLOAD_KEY: ""
  FILE_UPLOAD_SECRET: ""
