apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::{accountid}:role/{roleName}
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::accountid:user/username
      username: username
      groups:
        - system:masters
    - userarn: arn:aws:iam::accountid:user/username
      username: username
      groups:
        - system:masters
